### ISSUE TITLE
Rendering in Travis CI

### ISSUE THREAD

**Issue by theofidry** [qossmic/deprecation-detector#108]
It would be nice if the CLI output would fit in small screens. Obviously not asking for making it readable on a phone but at least on a terminal like Travis CI or AppVeyor:

<img width="926" alt="screen shot 2016-03-06 at 13 12 40" src="https://cloud.githubusercontent.com/assets/5175937/13554342/5b96ee52-e39d-11e5-97c2-a00b78e65116.png">

**Comment by iltar** [comment]
It would be cool to have a smaller table indeed, it would also make pasting things on GH easier.

**Comment by MarvinKlemp** [comment]
I started to develop #109 but wasn't really happy with it.
What about #117 ?

**Comment by smoench** [comment]
@MarvinKlemp #117 has been merged. This issue could be closed, right?
